name: Deploy Backend (BE Only)
on:
  push:
    branches: ['main']
    paths: ['be/**']
  workflow_dispatch:

jobs:
  deploy-be:
    name: âš™ï¸ Deploy BE
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get code
      uses: actions/checkout@v4
    
    - name: ğŸ“‚ Sync BE to Host
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        local-dir: be/
        server-dir: /htdocs/
        
        # --- QUAN TRá»ŒNG: Äáº·t tÃªn sá»• riÃªng cho BE ---
        state-name: .be-sync.json
        # ------------------------------------------
        
        delete: "false"
        
        exclude: |
          **/.git*
          **/.git/**