name: Deploy Backend (BE Only)
on:
  push:
    branches: ['main']
    paths: ['be/**']
  workflow_dispatch:

jobs:
  deploy-be:
    name: âš™ï¸ Deploy BE
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get code
      uses: actions/checkout@v4
    
    - name: ğŸ“‚ Sync BE to Host
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        # Láº¥y file Tá»ª folder be
        local-dir: be/
        
        # Äáº©y VÃ€O folder htdocs
        server-dir: /htdocs/
        
        # --- QUAN TRá»ŒNG NHáº¤T: DÃ’NG NÃ€Y Cáº¤M XÃ“A FILE Cá»¦A FRONTEND ---
        delete: "false"
        # -----------------------------------------------------------
        
        exclude: |
          **/.git*
          **/.git/**