name: Deploy Frontend (FE Only)
on:
  push:
    branches: ['main']
    paths: ['fe/**']
  workflow_dispatch:

jobs:
  deploy-fe:
    name: ğŸš€ Deploy FE
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get code
      uses: actions/checkout@v4
    
    - name: ğŸ“‚ Sync FE to Host
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        # Láº¥y file Tá»ª folder fe
        local-dir: fe/
        
        # Äáº©y VÃ€O folder htdocs
        server-dir: /htdocs/
        
        # --- QUAN TRá»ŒNG NHáº¤T: DÃ’NG NÃ€Y Cáº¤M XÃ“A FILE  BACKEND ---
        delete: "false"
        # ----------------------------------------------------------
        
        exclude: |
          **/.git*
          **/.git/**